# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-12 16:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('d3vis', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GenomicData',
        ),
    ]
