# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-13 09:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('d3vis', '0004_auto_20161113_0849'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='document',
            field=models.FileField(upload_to='FilesToProcess/'),
        ),
    ]
